excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
line_length:
  warning: 160
  ignores_function_declarations: true
  ignores_urls: true
file_length:
  warning: 800
  error: 1200
type_body_length:
  warning: 400
  error: 500
function_body_length:
  warning: 75
  error: 200
trailing_comma:
  mandatory_comma: true
identifier_name:
  validates_start_with_lowercase: false
  allowed_symbols: ["_"]
cyclomatic_complexity:
  ignores_case_statements: true
disabled_rules:
  - opening_brace
  - identifier_name
  - nesting
  - inclusive_language
